# Generated by DaoMake: DO NOT EDIT!
# Targeting platform macosx.

all: wrap/dao_OpenGL.h libdao_opengl.dylib

.PHONY: test
test: wrap/dao_OpenGL.h libdao_opengl.dylib subtest 


DAOMAKE = /Users/min/Projects/dao/tools/daomake/bootstrap/daomake


HEADERS_BF72 = wrap/dao_OpenGL.h


CFLAGS_C7AA =-ggdb -O0 -DDEBUG -fPIC -I../../kernel/ -DDAO_WITH_NUMARRAY -DDAO_WITH_DECORATOR -DDAO_WITH_THREAD -DDAO_WITH_CONCURRENT -DCHANGESET_ID=\"FOS.810842e0ca3b\" -DBSD=2 -DMACOSX=3 -DUNIX=1 -I. -I../../kernel/ -I../../ -I/System/Library/Frameworks/OpenGL.framework/Headers 


LFLAGS_3F5E =-ggdb -lm -lpthread -framework OpenGL -dynamiclib -install_name @rpath/libdao_opengl.dylib -undefined dynamic_lookup


DaoMake.Objs/dao_OpenGL.c.7F83.o: wrap/dao_OpenGL.c $(HEADERS_BF72)
	$(CC) $(CFLAGS_C7AA) -c wrap/dao_OpenGL.c -o DaoMake.Objs/dao_OpenGL.c.7F83.o

DaoMake.Objs/dao_OpenGL2.c.7B6C.o: wrap/dao_OpenGL2.c $(HEADERS_BF72)
	$(CC) $(CFLAGS_C7AA) -c wrap/dao_OpenGL2.c -o DaoMake.Objs/dao_OpenGL2.c.7B6C.o

DaoMake.Objs/dao_OpenGL3.c.7B48.o: wrap/dao_OpenGL3.c $(HEADERS_BF72)
	$(CC) $(CFLAGS_C7AA) -c wrap/dao_OpenGL3.c -o DaoMake.Objs/dao_OpenGL3.c.7B48.o


OBJECTS_5EF6 =DaoMake.Objs/dao_OpenGL.c.7F83.o DaoMake.Objs/dao_OpenGL2.c.7B6C.o DaoMake.Objs/dao_OpenGL3.c.7B48.o


wrap/dao_OpenGL.h:  opengl.c 
	@$(DAOMAKE) mkdir2 ./wrap/
	../../tools/clangdao/clangdao -I/System/Library/Frameworks/OpenGL.framework/Headers opengl.c -o wrap/


libdao_opengl.dylib: $(OBJECTS_5EF6)
	$(CC) $(OBJECTS_5EF6) $(LFLAGS_3F5E)  -o libdao_opengl.dylib

subtest:

.PHONY: subtest

TESTSUM =/Users/min/Projects/dao/daotest_result_summary.txt

testsum:

.PHONY: testsum

install:
	$(DAOMAKE) mkdir2 /usr/local/lib/dao
	$(DAOMAKE) mkdir2 /usr/local/lib/dao/modules
	$(DAOMAKE) copy libdao_opengl.dylib /usr/local/lib/dao/modules


uninstall:
	$(DAOMAKE) remove /usr/local/lib/dao/modules


.PHONY: install uninstall

clean:
	$(DAOMAKE) remove $(OBJECTS_5EF6)

.PHONY: clean

distclean:
	$(DAOMAKE) remove DaoMake.Objs

.PHONY: distclean

